name: Frontend Build and Push
on:
  pull_request:
    branches: ["dev"]
    paths:
      - 'frontend/**'
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'
  workflow_dispatch:
env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: samikshap85/frontend

jobs:
  commitlint:
    runs-on: [frontend]
    if: github.event_name == 'pull_request' && (github.head_ref == 'feature' || startsWith(github.head_ref, 'feature/')) && github.base_ref == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Conventional Commit Check
      #   uses: wagoid/commitlint-github-action@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install Commitlint
        run: |
          npm install --save-dev @commitlint/cli @commitlint/config-conventional
      - name: Add commitlint config
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Run Commitlint
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s" | npx commitlint
      
  check_lint:
    runs-on: [frontend]
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature') && github.base_ref == 'dev'
    needs: ["commitlint"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages of frontend
        working-directory: ./frontend
        run: yarn
      - name: Run lint on frontend
        working-directory: ./frontend
        run: yarn lint
  
  build_docker:
    runs-on: [frontend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      
      - name: Cache docker layer for frontend
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-frontend
          key: ${{ runner.os }}-buildx-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-frontend-

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Frontend App
        working-directory: ./frontend
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
        run: yarn install && yarn build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          destination_dir: ./

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          # load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-latest
          cache-from: type=local,src=/tmp/.buildx-cache-frontend
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend
      
      #------------------------------------------------------#
      - name: Save Docker image for frontend
        run: |
          docker save ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-latest -o frontend.tar

      - name: Upload frontend image tar
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend.tar
      #------------------------------------------------------#
      
      - name: Save frontend build artifact
        run: |
          mkdir -p artifacts/frontend
          find frontend/dist -type f ! -regex '.*[:\"<>|*?].*' -exec cp --parents {} artifacts/frontend/ \;

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: artifacts/frontend
      
      
