name: Semgrep Scan and Report Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Semgrep scan
        run: |
          semgrep --config "p/javascript" --config "p/react" --config "p/nodejs" . --json > semgrep-report.json

      - name: Generate HTML report from JSON
        run: |
          mkdir -p semgrep-reports
          python3 generate_html_report.py
          cp semgrep-report.json semgrep-reports/

      - name: Upload Semgrep reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-reports
          path: semgrep-reports/

      - name: Deploy to GitHub Pages via gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: semgrep-reports
          publish_branch: gh-pages
          destination_dir: semgrep/scan
