name: Semgrep Scan and Report Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Semgrep scan
        run: |
          semgrep --config "p/javascript" --config "p/react" --config "p/nodejs" . --json > semgrep-report.json

      - name: Generate HTML report
        run: |
          mkdir -p semgrep-reports
          echo '<html><head><meta charset="UTF-8"><title>Semgrep Report</title></head><body><h1>Semgrep Report</h1><pre>' > semgrep-reports/index.html
          cat semgrep-report.json | jq '.' >> semgrep-reports/index.html
          echo '</pre></body></html>' >> semgrep-reports/index.html

      - name: Deploy to GitHub Pages via gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: semgrep-reports
          publish_branch: gh-pages
          destination_dir: semgrep/scan
