name: Trivy Security Scan

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: [frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy (Fedora)
        run: |
          sudo dnf install -y wget rpm
          wget https://github.com/aquasecurity/trivy/releases/download/v0.64.1/trivy_0.64.1_Linux-64bit.rpm
          sudo rpm -ivh trivy_0.64.1_Linux-64bit.rpm

      - name: Download Trivy HTML template
        run: |
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
      
      - name: Scan images with Trivy HTML template
        run: |
          mkdir -p trivy-reports
          for img in backend1 backend2 frontend; do
            trivy image \
              --format template \
              --template "@html.tpl" \
              --output "trivy-reports/$img.html" \
              "docker.io/samikshap85/$img:dev-latest"
          done

      
      # - name: Run Trivy scan on backend1 image
      #   run: |
      #     mkdir -p trivy-reports
      #     trivy image --format html --output trivy-reports/backend1.html docker.io/samikshap85/backend1:dev-latest

      # - name: Run Trivy scan on backend2 image
      #   run: |
      #     trivy image --format html --output trivy-reports/backend2.html docker.io/samikshap85/backend2:dev-latest

      # - name: Run Trivy scan on frontend image
      #   run: |
      #     trivy image --format html --output trivy-reports/frontend.html docker.io/samikshap85/frontend:dev-latest

      # - name: Upload Trivy reports as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-html-reports
      #     path: trivy-reports
      
      - name: Create index page for scan reports
        run: |
          echo "<h1>Trivy Scan Reports</h1><ul>" > trivy-reports/index.html
          for f in backend1.html backend2.html frontend.html; do
            echo "<li><a href='$f'>$f</a></li>" >> trivy-reports/index.html
          done
          echo "</ul>" >> trivy-reports/index.html

      - name: Deploy scan reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./trivy-reports
          publish_branch: gh-pages
          destination_dir: scan

      
      

      

      


      